### ISSUE TITLE
TechEmpower benchmarks

### ISSUE THREAD

**Issue by tomchristie** [kennethreitz/responder#31] opened 2018-10-13 18:52 UTC
This’d be a good one for a contributor to jump on.

Adding TechEmpower benchmarks for Responder. I’d suggest copying the starlette case, and adapting it accordingly. https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Python/starlette

PR would be against the TechEmpower repo, not here. They run continuos benchmarks against the suite, so the performance section could be updated once there’s a run that includes Responder.

You’ll want to use an async DB connector, as per the starlette case.

**Comment by 5hirish** [comment] 2018-10-13 20:40
Working on it, except I am getting 404s for requests defined following the first API request.
```
import responder

api = responder.API()

@api.route("/hello")
async def greet_world(req, resp):
    resp.text = f"Hello, world!"

@api.route("/bye")
async def greet_world(req, resp):
    resp.media = {"data": "Bye, world!"}

if __name__ == '__main__':
    api.run()
```
Here `/hello` returns 200 but `/bye` returns 404. If I change the sequence of declaration then `/bye` works.

**Comment by 5hirish** [comment] 2018-10-13 20:42
https://github.com/5hirish/FrameworkBenchmarks/blob/responder/frameworks/Python/responder/app.py

**Comment by kennethreitz** [comment] 2018-10-13 22:31
that's because you named your function the same thing twice

**Comment by 5hirish** [comment] 2018-10-13 23:36
@kennethreitz sorry, that was copy-paste typo, fixed it, but still, the issue is reproducible, can try running the `app.py` from my fork. Or am I declaring something wrong here?

**Comment by 5hirish** [comment] 2018-10-14 16:17
I have created a PR on the TechEmpower repo: (Still haven't resolved the above mentioned issue. Maybe it is happening only for my system...?) https://github.com/TechEmpower/FrameworkBenchmarks/pull/4122

**Comment by sheb** [comment] 2018-10-14 16:46
@5hirish I had the same problem with `v.0.0.3`, but seems to be fixed on `master`

**Comment by 5hirish** [comment] 2018-10-14 18:37
Thanks for informing... BTW I am getting this `responder: ERROR: Framework is not accepting requests from client machine` in the CI console might be due to the above issue I guess...In my local, at least the first API was working...Will have to wait for the next release.

**Comment by 5hirish** [comment] 2018-10-16 15:42
Tried running the docker file in local, to pin point the error in docker run. I executed the the gunicorn task separately 
`gunicorn app:app --log-level debug -k uvicorn.workers.UvicornWorker -c responder_conf.py`
I am getting the following error:
```
Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/home/felix/.pyenv/versions/3.6.5/envs/pyw365/lib/python3.6/site-packages/uvicorn/lifespan.py", line 29, in run
    await self.asgi(self.receive, self.send)
  File "/home/felix/.pyenv/versions/3.6.5/envs/pyw365/lib/python3.6/site-packages/uvicorn/middleware/message_logger.py", line 51, in __call__
    inner = self.app(self.scope)
  File "/home/felix/.pyenv/versions/3.6.5/envs/pyw365/lib/python3.6/site-packages/responder/api.py", line 100, in __call__
    path = scope["path"]
KeyError: 'path'

```

**Comment by 5hirish** [comment] 2018-10-17 10:00
Will update the benchmarks when the PR is approved and merged. @tomchristie responder doesn't need Jinja dependency but the `api.template()` call was not taking template file path as an argument, hence reverted to external Jinja dependency and usage. If this will affect the performance any form then let me know.

**Comment by tomchristie** [comment] 2018-10-17 20:56
@5hirish good work. They have a continuous benchmarking suite running, tho it has a turnover time of 2 or 3 days. Check https://tfb-status.techempower.com/ and you should see their latest results soon enough.

**Comment by therumbler** [comment] 2018-10-22 15:00
the Tech Empower benchmark has completed, and includes Responder's results now. 
https://www.techempower.com/benchmarks/#section=test&runid=a0d523de-091b-4008-b15d-bd4c8aa25066

**Comment by 5hirish** [comment] 2018-10-25 05:42
@tomchristie can close this issue. PR: Update ReadMe #130

**Closed** 2018-10-25 06:37 UTC
Labels: good first issue

**Comment by kennethreitz** [comment] 2018-10-31 11:03
@therumbler we were included in the last batch -- any idea why?

**Comment by tomchristie** [comment] 2018-11-01 21:14
I *guess* it must have just missed the round 17 cutoff.

**Comment by waghanza** [comment] 2018-11-08 14:34
@tomchristie I have tested **tfb**
+ Cloning https://github.com/TechEmpower/FrameworkBenchmarks
+ Updating deps -> pip3 install -r requirements.txt
+ Running -> gunicorn app:app -k uvicorn.workers.UvicornWorker -c responder_conf.py
leads me to a **socket.gaierror: [Errno -2] Name or service not known**
